export interface BriefData {
  project: {
    name: string
    type?: string
    cluster?: string
    created_at?: string
  }
  phases: Array<{
    id: string
    name: string
    description?: string
    order?: number
  }>
  features: Array<{
    id: string
    name: string
    description?: string
    phase_id?: string
    status?: string
  }>
  context?: string
  agentSummary?: string
}

// ─── Markdown template ────────────────
export function generateMarkdown(
  data: BriefData
): string {
  const now = new Date().toLocaleDateString(
    'en-US', { 
      year: 'numeric', 
      month: 'long', 
      day: 'numeric' 
    }
  )

  const lines: string[] = []

  // Header
  lines.push(`# ${data.project.name}`)
  lines.push(``)
  lines.push(
    `> Generated by Reminisce · ${now}`
  )
  lines.push(``)
  lines.push(`---`)
  lines.push(``)

  // Overview table
  lines.push(`## Overview`)
  lines.push(``)
  if (data.project.type) {
    lines.push(
      `**Type:** ${data.project.type}`
    )
  }
  if (data.project.cluster) {
    lines.push(
      `**Cluster:** ${data.project.cluster}`
    )
  }
  lines.push(
    `**Phases:** ${data.phases.length}`
  )
  lines.push(
    `**Features:** ${data.features.length}`
  )
  if (data.project.created_at) {
    lines.push(
      `**Created:** ${new Date(
        data.project.created_at
      ).toLocaleDateString()}`
    )
  }
  lines.push(``)

  // Context document
  if (data.context?.trim()) {
    lines.push(`---`)
    lines.push(``)
    lines.push(`## Project Context`)
    lines.push(``)
    lines.push('```')
    lines.push(data.context.trim())
    lines.push('```')
    lines.push(``)
  }

  // Phases + features
  if (data.phases.length > 0) {
    lines.push(`---`)
    lines.push(``)
    lines.push(`## Phases`)
    lines.push(``)

    const sortedPhases = [...data.phases].sort(
      (a, b) => (a.order ?? 0) - (b.order ?? 0)
    )

    sortedPhases.forEach((phase, i) => {
      lines.push(
        `### Phase ${i + 1} — ${phase.name}`
      )
      lines.push(``)
      if (phase.description) {
        lines.push(phase.description)
        lines.push(``)
      }

      // Features in this phase
      const phaseFeatures = data.features.filter(
        f => f.phase_id === phase.id
      )
      if (phaseFeatures.length > 0) {
        lines.push(`**Features:**`)
        lines.push(``)
        phaseFeatures.forEach(f => {
          const status = f.status 
            ? ` *(${f.status})*` 
            : ''
          lines.push(`- ${f.name}${status}`)
          if (f.description) {
            lines.push(
              `  ${f.description}`
            )
          }
        })
        lines.push(``)
      }
    })

    // Features not assigned to any phase
    const unassigned = data.features.filter(
      f => !f.phase_id || 
           !data.phases.find(
             p => p.id === f.phase_id
           )
    )
    if (unassigned.length > 0) {
      lines.push(`### Unassigned Features`)
      lines.push(``)
      unassigned.forEach(f => {
        lines.push(`- ${f.name}`)
      })
      lines.push(``)
    }
  }

  // Agent summary if provided
  if (data.agentSummary?.trim()) {
    lines.push(`---`)
    lines.push(``)
    lines.push(`## AI Analysis`)
    lines.push(``)
    lines.push(data.agentSummary.trim())
    lines.push(``)
  }

  // Footer
  lines.push(`---`)
  lines.push(``)
  lines.push(
    `*This brief was generated by [Reminisce]` +
    `(https://reminisce.io) — ` +
    `AI context orchestration for engineering teams.*`
  )

  return lines.join('\n')
}

// ─── Plain text (strip markdown) ──────
export function generatePlainText(
  data: BriefData
): string {
  return generateMarkdown(data)
    .replace(/#{1,6} /g, '')
    .replace(/\*\*(.*?)\*\*/g, '$1')
    .replace(/\*(.*?)\*/g, '$1')
    .replace(/`{3}[\s\S]*?`{3}/g, '')
    .replace(/`(.*?)`/g, '$1')
    .replace(/^> /gm, '')
    .replace(/^---$/gm, '─'.repeat(40))
    .replace(/\[([^\]]+)\]\([^)]+\)/g, '$1')
    .trim()
}

// ─── JSON export ───────────────────────
export function generateJSON(
  data: BriefData
): string {
  return JSON.stringify({
    exported_at: new Date().toISOString(),
    exported_by: 'Reminisce v2',
    project: data.project,
    phases: data.phases,
    features: data.features,
    context: data.context,
  }, null, 2)
}

// ─── Download helper ───────────────────
export function downloadFile(
  content: string,
  filename: string,
  mimeType: string
) {
  const blob = new Blob([content], 
    { type: mimeType })
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = filename
  document.body.appendChild(a)
  a.click()
  document.body.removeChild(a)
  URL.revokeObjectURL(url)
}

// ─── Clipboard helper ──────────────────
export async function copyToClipboard(
  text: string
): Promise<boolean> {
  try {
    await navigator.clipboard.writeText(text)
    return true
  } catch {
    // Fallback for older browsers
    const el = document.createElement('textarea')
    el.value = text
    el.style.position = 'absolute'
    el.style.left = '-9999px'
    document.body.appendChild(el)
    el.select()
    document.execCommand('copy')
    document.body.removeChild(el)
    return true
  }
}
